# Generated by Django 2.1.2 on 2019-05-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emCheckItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('checkID', models.CharField(max_length=5, unique=True)),
                ('explain', models.CharField(max_length=200)),
                ('cycleTime', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='emCheckRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('ipAddr', models.GenericIPAddressField()),
                ('giUser', models.CharField(max_length=20)),
                ('checkLine', models.CharField(max_length=5)),
                ('checkStation', models.CharField(max_length=50)),
                ('checkItems', models.TextField()),
                ('checkOwner', models.CharField(max_length=20)),
                ('checkDate', models.DateField()),
                ('checkFileName', models.CharField(max_length=200)),
                ('checkFile', models.FileField(upload_to='em_app/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='emFatpDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('checkID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em_app.emCheckItem')),
                ('lastRecordID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='em_app.emCheckRecord')),
            ],
        ),
        migrations.CreateModel(
            name='emLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='emStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('enName', models.CharField(max_length=2, unique=True)),
                ('orderNum', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='emline',
            name='station',
            field=models.ManyToManyField(to='em_app.emStation'),
        ),
        migrations.AddField(
            model_name='emfatpdetail',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em_app.emLine'),
        ),
        migrations.AddField(
            model_name='emfatpdetail',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em_app.emStation'),
        ),
        migrations.AddField(
            model_name='emcheckitem',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkItems', to='em_app.emStation'),
        ),
    ]
