# Generated by Django 2.1.2 on 2019-05-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emcheckitem',
            options={'verbose_name': '檢查項目', 'verbose_name_plural': '檢查項目'},
        ),
        migrations.AlterModelOptions(
            name='emline',
            options={'verbose_name': '線別', 'verbose_name_plural': '線別'},
        ),
        migrations.AlterModelOptions(
            name='emstation',
            options={'verbose_name': '站別', 'verbose_name_plural': '站別'},
        ),
        migrations.AlterField(
            model_name='emcheckitem',
            name='checkID',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
