# Generated by Django 2.1.2 on 2019-05-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_app', '0002_auto_20190520_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='emSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('line', models.CharField(max_length=5)),
                ('day', models.DateField()),
                ('periods', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='emline',
            name='lineOwner',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
