# Generated by Django 2.1.7 on 2019-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_app', '0003_auto_20190530_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='emcheckitem',
            name='size',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
